A better version of the pull request from hoshsadiq that handles being killed while waiting on xpra

diff --git a/run_scaled b/run_scaled
--- a/run_scaled
+++ b/run_scaled
@@ -6,25 +6,22 @@
 export XDG_MENU_PREFIX="gnome-" 
 SCALING_FACTOR=2
 USE_OPENGL="auto"
-SLEEPTIME=1
 PERFORMANCE_OPTIONS="--encoding=rgb --mmap=yes --compress=0"
 
+# this gets setup just before we start xpra, so that we make sure it's stopped if possible
+function cleanup {
+  echo "Making sure xpra is stopped"
+  xpra stop "$DISPLAYNUM" >/dev/null 2>&1
+}
+
 print_help() {
-    echo "Usage: run_scaled [--scale=scaling_factor] [--opengl=auto|yes|no] [--sleep=sleeptime] application"
+    echo "Usage: run_scaled [--scale=scaling_factor] [--opengl=auto|yes|no] application"
     echo ""
     echo "--scale  Sets the factor the application is scaled by. Fractional scales are"
     echo "         supported. It is set to 2 by default."
     echo "--opengl Sets whether xpra should use opengl for rendering. If you get rendering"
     echo "         errors, especially when the window is resized, try setting it to no. It"
     echo "         is set to auto by default."
-    echo "--sleep  Sets how many seconds to wait after starting xpra before attaching to"
-    echo "         the xpra session. It is set to 1 by default."
-    echo "         You might need to increase the value if your machine is particularly"
-    echo "         slow and attaching fails with a message like"
-    echo ""
-    echo "             InitException: cannot find any live servers to connect to"
-    echo "             xpra initialization error:"
-    echo "              cannot find any live servers to connect to"
     echo ""
 }
 
@@ -42,10 +39,6 @@ while true
             ;;
             --opengl=*)
                 USE_OPENGL="${1#*=}"
-                shift
-            ;;
-            --sleep=*)
-                SLEEPTIME="${1#*=}"
                 shift
             ;;
             --)
@@ -76,7 +69,15 @@ UNSCALED_RESOLUTION="$( awk "BEGIN {print int($UNSCALED_RESOLUTION_X / $SCALING_
 #--start-new-commands=no causes xpra to not even try to read xdg menus, starting up much faster, and not running into the gnome- bug mentioned above
 
 DISPLAYNUM=:$(shuf -i 10000-99999999 -n 1)
+
+# setup the trap to cleanup xpra
+trap cleanup EXIT
+
 ESCAPED_PARAMS=$(printf '%q ' "$@")
 xpra start "$DISPLAYNUM" --xvfb="Xvfb +extension Composite -screen 0 ${UNSCALED_RESOLUTION}x24+32 -nolisten tcp -noreset  -auth \$XAUTHORITY" --env=GDK_SCALE=1 --env=GDK_DPI_SCALE=1 --env=QT_SCALE_FACTOR=1 --env=QT_AUTO_SCREEN_SCALE_FACTOR=0 --start-child="$ESCAPED_PARAMS" --exit-with-children --start-new-commands=no
-sleep "$SLEEPTIME"
+
+until xpra info "$DISPLAYNUM" >/dev/null 2>&1; do
+  sleep 0.1
+done
+
 XGDK_SCALE=1 PRA_EXPORT_ICON_DATA=0 xpra attach "$DISPLAYNUM" "--desktop-scaling=$SCALING_FACTOR" "--opengl=$USE_OPENGL" $PERFORMANCE_OPTIONS || xpra stop "$DISPLAYNUM"
